# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('eps', models.CharField(max_length=30)),
                ('pension', models.CharField(max_length=30)),
                ('arl', models.CharField(max_length=30)),
                ('rango', models.IntegerField()),
                ('costo', models.FloatField()),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Afiliados',
            },
        ),
        migrations.CreateModel(
            name='Benefiniciario',
            fields=[
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.CharField(max_length=30)),
                ('parentesco', models.CharField(max_length=30)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Afiliado')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=30)),
                ('valor', models.FloatField()),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Afiliado')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioAdministrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Usuario Administrativo',
                'verbose_name_plural': 'Usuario Administrativos',
            },
        ),
    ]
